- src/client/src/commons/form/borehole/segments/coordinatesSegment.js
#59 
Die Verwendung der http url für die Transformation der Koordinaten führte zu Problemen auf Dev/Test.  Neu wird eine https url verwendet.
> Use https instead of http for coordinate transformation

- .github/workflows/ci.yml
And update the GitHub Action version along the way.
> Disable cypress screenshots during CI build

- CHANGELOG.md
- src/client/src/commons/map/pointComponent.js
Previously the address was queried on every single move while dragging the point on the map causing the application to crash. Now the address gets only queried once when the point has been changed.
Fixes #266
> Fix app crash when changing the borehole location

- docker-compose.yml
in development environment in order to prevent timouts when seeding layers at startup.
#34
> Extend sql command timeout

- src/client/cypress.config.js
Die erzeugten Screenshots zeigen nun das ganze UI an.
> Increase cypress viewport and screenshot size

- src/client/cypress/e2e/editor/lithologicalDescription.cy.js
- src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionInput.js
- src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionLayers.js
- src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
Resolves #389 
Wir haben uns dazu entschieden die Benutzerführung so anzupassen, dass Überschneidungen gar nicht erst eingegeben werden können und wir somit die Fehler vermeiden  statt komplizierten Fehlermeldungen mit Lösungsoptionen anzuzeigen. 
Im Gegensatz zu Lücken in der Schicht sind Überlappungen ja kein plausibles Szenario in der Schichtenabfolge.
Den Benutzenden stehen trotzdem alle Eingabeoptionen zur Verfügung.
> Reduce depth options to avoid overlaps

- CHANGELOG.md
- src/client/src/commons/form/profile/components/profileInstrument/api/index.js
- src/client/src/commons/form/profile/hooks/useCasingList.js
Reverts geoadmin/suite-bdms#451
This change had no effect and causes unnecessary cache invalidation requests.
#426
> Revert "Use react-query for fetching instruments"

- src/api/Controllers/StratigraphyController.cs
- tests/StratigraphyControllerTest.cs
Related to: https://github.com/geoadmin/suite-bdms/issues/471
Beim Kopieren von Stratigraphien ist das mitkopieren der neuen Chronostratigraphy vergessen gegangen.
> Copy chronostratigraphy when copying stratigraphy

- .github/workflows/release.yml
Due to updated workflow trigger in #478 a dedicated personal access token is not needed anymore.
**remark**: _GH_TOKEN_ und _GITHUB_TOKEN_ sind gemäss [Doku](https://cli.github.com/manual/gh_help_environment) der GH CLI beide korrekt, resp. es müssen daher nicht beide gesetzt werden.
Das Secret _GH_GEOW_BUILD_ werde ich gleich noch aus der GitHub Umgebgung entfernen.
> Use built-in GITHUB_TOKEN in release workflow

- src/client/cypress.config.js
> Enable auto retries for failing cypress tests

- src/api/Dockerfile
By default the port 8080 is used in .NET 8 docker images: https://andrewlock.net/exploring-the-dotnet-8-preview-updates-to-docker-images-in-dotnet-8/#asp-net-core-apps-now-use-port-8080-by-default
#854
> Set ASPNETCORE_HTTP_PORTS to port 80

- src/api-legacy/v1/borehole/patch.py
- src/client/src/api-lib/reducers/index.js
- src/client/src/commons/form/borehole/boreholeForm.js
The field was part of an obsolete db view.
Resolves #498
> Remove obsolete percentage field

- src/api-legacy/v1/borehole/profile/producer.py
- src/api-legacy/v1/borehole/stratigraphy/producer.py
And obsolete CREATE action handling as it is already migrated to the .NET API.
Resolves #893
> Remove unused CHECK action

- src/api/BoreholeLockService.cs
- src/api/Controllers/CompletionController.cs
- src/api/Controllers/StratigraphyController.cs
- tests/BoreholeLockServiceTest.cs
Do not return UnauthorizedAccessExceptions inside the method, return a boolean indicating the lock status instead.
Working on #939
> Simplify IsBoreholeLockedAsync

- src/api/BdmsContext.cs
- src/api/Migrations/20240306151944_AddMissingMigration.Designer.cs
- src/api/Migrations/20240306151944_AddMissingMigration.cs
Adds a missing migrations for the changed nullability of precision attributes and fixes a problem, where when adding a new migration the delete behaviour "Cascade" was always added for casing elements.
> Add missing migration

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
If a pull requests gets created by github-actions (e.g. mark-version-as-released), dependent actions are not executed  automatically (this is by design). With this change, we are able to manually trigger the actions needed to pass the required pr status checks.
> Enable to trigger a  workflow manually

- src/client/cypress/e2e/editor/dataCards.cy.js
- src/client/src/AppTheme.ts
- src/client/src/components/form/formResultTableDisplay.tsx
- src/client/src/components/legacyComponents/domain/dropdown/domainDropdown.jsx
- src/client/src/pages/detail/detailHeader.tsx
- src/client/src/pages/detail/detailPage.tsx
- src/client/src/pages/detail/detailPageContent.jsx
- src/client/src/pages/detail/form/completion/casingDisplay.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithology.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyAttributes/lithologyAttributeList/lithologyAttributeList.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyAttributes/lithologyAttributes.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyInfo/infoList/InfoList.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyInfo/lithologyInfo.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyLayers/lithologyLayersList/lithologyLayersList.jsx
- src/client/src/pages/detail/form/stratigraphy/lithology/lithologyLayers/lithologyLayersList/styles.js
Mit dem Viewer Login und dem anonymen Modus waren zum Teil Dropdowns und Radiobuttons aktiv, die readonly hätten sein müssen. Tatsächlich editieren war zwar bereits unmöglich, die Inputs waren allerdings trotzdem aktiv.
@tschumpr irgendwo auf dem Weg diverser Theme-Anpassungen ist der Style der Tables in Completion und Hydrogeology kaputt gegangen. Habe versucht es zu fixen, aber ich weiss nicht mehr genau wie es mal aussah.
> Fix editing and lock check

- src/client/package-lock.json
Fixes https://github.com/swisstopo/swissgeol-boreholes-suite/security/dependabot/116
> Bump path-to-regexp from 1.8.0 to 1.9.0

- src/client/cypress/e2e/detailPage/boreholeform.cy.js
- src/client/public/locale/de/common.json
- src/client/public/locale/en/common.json
- src/client/public/locale/fr/common.json
- src/client/public/locale/it/common.json
- src/client/src/components/form/simpleBooleanSelect.tsx
- src/client/src/components/form/simpleDomainSelect.tsx
- src/client/src/components/form/simpleFormInput.tsx
- src/client/src/pages/detail/detailPageContent.jsx
- src/client/src/pages/detail/form/location/coordinatesSegment.tsx
- src/client/src/pages/detail/form/location/elevationSegment.tsx
- src/client/src/pages/detail/form/location/restrictionSegment.tsx
@danjov mit den Standard Formkomponenten gab es Probleme, das die Werte zt nicht richtig zurückgesetzt wurden, als ich jetzt das Location Form umgestellt habe und bisher noch das "Save on Change" beibehalten habe. Etwas unglücklich, dass es auch keiner unserer Tests gecached hat. Ich brauche jetzt hier diesen Workaround bis das neue Speicherverhalten umgesetzt ist.
> Fix form reset

- src/api/Migrations/20230602151701_UpdateLithostratiCodelist.cs
Remove database name in `UPDATE` statement.
This only works in environments, where the _borehole_ database name is _bdms_.
This assumption does not apply to all environments, especially the new ones.
> Fix existing database migration

- CHANGELOG.md
- src/client/src/components/map/pointComponent.jsx
- src/client/src/pages/detail/detailPage.tsx
- src/client/src/pages/detail/detailPageContent.tsx
- src/client/src/pages/detail/form/location/coordinatesSegment.tsx
- src/client/src/pages/detail/form/location/identifierSegment.tsx
- src/client/src/pages/detail/form/location/locationPanel.tsx
- src/client/src/pages/detail/form/location/locationPanelInterfaces.tsx
- src/client/src/pages/detail/form/location/locationSegment.tsx
> Fix responsivenes in detail view

- CHANGELOG.md
- src/client/cypress/e2e/filters/filter.cy.js
- src/client/src/pages/detail/detailHeader.tsx
- src/client/src/pages/overview/sidePanelContent/filter/statusFilter.jsx
> Fix status filter

- CHANGELOG.md
- src/client/src/pages/detail/form/borehole/boreholeForm.tsx
> Fix borehole tab layout

- src/client/cypress/e2e/detailPage/location.cy.js
- src/client/src/pages/detail/form/location/restrictionSegment.tsx
@danjov @Lehats 
Die sauberere Lösung wäre hier den Datentyp im Backend zu ändern. Damit das Datum gleich richtig zurückkommt. 
Das hier ist der Hotfix
> Restriction end date

- CHANGELOG.md
- src/client/src/pages/settings/editorSettings.tsx
> Fix layers display settings bug

- src/api/Controllers/BoreholeController.cs
- tests/api/Controllers/BoreholeControllerTest.cs
Aktuell wird das suffix nur dem OriginalName hinzugefügt und ist daher in der Tabelle und im Titel des Boreholes nicht mehr sichtbar.
> Add (Copy) to alternate name

- src/client/src/pages/detail/detailHeader.tsx
So that the translation can be loaded.
> Fix typo of export CSV button label

- src/client/cypress/e2e/detailPage/coordinates.cy.js
- src/client/src/pages/detail/form/location/locationSegment.tsx
> Fix coordinate update

- CHANGELOG.md
- src/client/src/components/form/formSelect.tsx
Anmerkung von Michael aus dem UX Meeting
> Hide dropdown arrows if form is not editable

- tests/api/BoreholeFileCloudServiceTest.cs
- tests/api/BoreholeLockServiceTest.cs
- tests/api/Controllers/BoreholeControllerTest.cs
- tests/api/Controllers/ImportControllerTest.cs
- tests/api/Controllers/SettingsControllerTest.cs
- tests/api/Controllers/StratigraphyControllerTest.cs
- tests/api/Helpers.cs
These changes cut the test execution time almost in half. Further improvements can be made as soon as #1944 is merged.
> Simplify and optimize borehole retrieval in test code

- CHANGELOG.md
- src/extern-sync/SyncContextExtensions.cs
- src/extern-sync/Tasks/SyncBoreholesTask.cs
- src/extern-sync/db-init/01_set_workflow_status.sh
- tests/extern-sync/SyncContextExtensionsTest.cs
- tests/extern-sync/Tasks/SyncBoreholesTaskTest.cs
- tests/extern-sync/TestSyncContextExtensions.cs
Also update the term which is used in functions and comments to describe the status of a borehole.
Resolves #2296
> Sync boreholes with status reviewed or published
