swisstopo/swissgeol-boreholes-suite

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml
=> Add CodeQL and Dependency Review workflows

docker-compose.yml, src/client/Dockerfile
=> Improve development environment

src/client/src/pages/settings/resourcesSettings.js
https://github.com/geoadmin/suite-bdms/issues/56
=> Update "Dokumentation" page in settings

src/client/src/stratigraphy/stratigraphy.js
https://github.com/geoadmin/suite-bdms/issues/57
=> Fix stratigraphy

src/client/src/commons/form/profile/components/profileAttributes/components/profileAttributeList/profileAttributeList.js
https://github.com/geoadmin/suite-bdms/issues/13
=> Add missing option "Keine Angabe" for layer_striae

src/client/src/commons/table/boreholeEditorTable.js, src/client/src/commons/table/boreholeTable.js
https://github.com/geoadmin/suite-bdms/issues/19
=> Update total_depth attribute reference in table

src/api/Dockerfile
otherwise health-check doesn't work
#34
=> Add missing package

src/client/src/stratigraphy/stratigraphy.js
https://github.com/geoadmin/suite-bdms/issues/81
=> Improve stratigraphy viewer

.github/workflows/release.yml, CHANGELOG.md
=> Add changelog

.devcontainer/devcontainer.json, README.md, docker-compose.yml, src/api/Dockerfile, src/api/Properties/launchSettings.json
=> Improve dev container

CHANGELOG.md, src/client/src/pages/term/accept.js
fixes https://github.com/geoadmin/suite-bdms/issues/68
=> Fix terms of service

CHANGELOG.md, src/client/public/index.html, src/client/src/pages/settings/dataLoader.js
Fixes https://github.com/geoadmin/suite-bdms/issues/67
=> Always fetch up to date login screen text

README.md, config/pgadmin4-servers.json, docker-compose.yml
https://github.com/geoadmin/suite-bdms/issues/28
=> Enable automatic login in pgAdmin4

config/create-user.sql
=> Add create-user script

CHANGELOG.md, src/client/cypress/e2e/filter.cy.js, src/client/src/commons/form/domain/dropdown/domainDropdown.js
Fixes https://github.com/geoadmin/suite-bdms/issues/20
=> Fix filter dropdowns not updating

CHANGELOG.md, src/client/src/pages/settings/explorerSettings.js
Fixes https://github.com/geoadmin/suite-bdms/issues/21
=> Fix appearance setting label

CHANGELOG.md, src/client/cypress/e2e/editor/location.cy.js, src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/menu/menuComponent.js, src/client/src/commons/table/boreholeEditorTable.js
Fixes https://github.com/geoadmin/suite-bdms/issues/26
=> Fix error highlight of identifier fields

CHANGELOG.md, src/client/cypress/e2e/editor/bulkedit.cy.js, src/client/src/commons/form/multiple/multipleForm.js
Fixes https://github.com/geoadmin/suite-bdms/issues/24
=> Improve bulk edit

src/client/cypress/e2e/codeList.cy.js, src/client/src/pages/settings/editor/codeListSettings.js
=> Improve codelist translation UI

CHANGELOG.md, src/client/cypress.config.js, src/client/cypress/e2e/editor/bulkedit.cy.js, src/client/cypress/e2e/editor/instrumentation.cy.js, src/client/cypress/e2e/editor/location.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/form/profile/components/profileHeader/components/profileHeaderList/profileHeaderList.js, src/client/src/commons/form/profile/components/profileHeader/profileHeader.js, src/client/src/commons/form/profile/components/profileInstrument/components/instrument/Instrument.js, src/client/src/commons/form/profile/components/profileInstrument/profileInstrument.js, src/client/src/commons/form/profile/profile.js, src/client/src/commons/menu/editor/menuEditorForm.js
=> Fix instrument tab

CHANGELOG.md, src/client/cypress/e2e/admin/userAdministration.cy.js, src/client/src/pages/settings/adminSettings.js
=> Description enable user

CHANGELOG.md, src/api-legacy/v1/user/create.py, src/client/cypress/e2e/admin/userAdministration.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/src/pages/settings/adminSettings.js
=> Fix admin user

src/client/src/index.js
=> Use React 18 render API

src/api/Controllers/BoreholeController.cs, tests/BoreholeControllerTest.cs
Fixes https://github.com/geoadmin/suite-bdms/issues/25
=> Keep original CreatedBy user when copying borehole

CHANGELOG.md, src/client/cypress/e2e/app.cy.js, src/client/src/commons/menu/menuComponent.js
=> Display environment specific app title

CHANGELOG.md, src/api-legacy/v1/basehandler.py, src/api/Authentication/BasicAuthenticationHandler.cs, src/api/Authentication/PolicyNames.cs, src/api/Controllers/UserController.cs, src/api/Program.cs, src/client/cypress/e2e/app.cy.js, src/client/src/api-lib/actions/settings.js, src/client/src/commons/form/loginPreview.js, src/client/src/pages/settings/dataLoader.js, tests/BoreholeControllerTest.cs
=> Remove anonymous login option

CHANGELOG.md, src/client/src/commons/form/profile/components/profileHeader/profileHeader.js
=> Always show Show All button

src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js, src/client/src/commons/form/borehole/segments/boreholeGeneralSegment.js, src/client/src/commons/form/borehole/segments/cantonMunicipalitySegment.js, src/client/src/commons/form/borehole/segments/indentifierSegment.js, src/client/src/commons/form/borehole/segments/locationSegment.js, src/client/src/commons/form/borehole/segments/nameSegment.js, src/client/src/commons/form/borehole/segments/restrictionSegment.js
Bevor wir die Änderungen am Räumlichen Bezugssystem angehen habe ich das "borehole form" in Komponenten aufgeteilt um es übersichtlicher zu machen.
=> Refactor borehole form

CHANGELOG.md, src/api-legacy/v1/utils/sendmail.py
=> Fix sending feedback e-mail

CHANGELOG.md, src/client/src/commons/form/profile/components/profileInstrument/styles.js
=> Improve spacing

src/api/BDMS.csproj
Resolves https://github.com/geoadmin/suite-bdms/security/dependabot/81
=> Bump System.Data.SqlClient from 4.8.3 to 4.8.5

config/shift-coordinates.sql
=> Add spatial reference system migration script

src/api/Controllers/MigrateController.cs, src/api/Program.cs
=> Add new migration endpoint

CHANGELOG.md, src/client/src/commons/map/mapComponent.js
=> Cluster point layer on overview map

CHANGELOG.md, src/client/src/commons/form/profile/components/profileInstrument/components/instrument/Instrument.js
=> Fix selection of instruments when no casing is selected

src/client/src/commons/form/profile/components/profileInstrument/components/instrument/Instrument.js
#14 
Gibt kein changelog da es noch eine Verbesserung zu einem bereits gemergten fix ist ;)
=> Fix asynchronous behaviour when selecting instrument casings

CHANGELOG.md, src/client/src/commons/form/borehole/segments/locationSegment.js, src/client/src/commons/map/pointComponent.js
=> Fix points disappearing

CHANGELOG.md, src/api-legacy/v1/action.py, src/client/cypress/e2e/identifierFilter.cy.js, src/client/src/commons/form/domain/dropdown/domainDropdown.js
=> Fix identifier filter

src/client/src/commons/map/pointComponent.js
=> Only change srs when coordinates change

CHANGELOG.md, src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js
=> Fix translation labels

CHANGELOG.md, src/client/cypress/e2e/codeList.cy.js, src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/pages/settings/editor/codeListSettings.js
=> Sort geol codes

src/client/src/api-lib/actions/borehole.js, src/client/src/commons/map/mapComponent.js
=> Fix not all points displayed

CHANGELOG.md, src/client/src/pages/settings/editor/codeListSettings.js
=> Fix order of codelists in translation UI

CHANGELOG.md, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js, src/client/src/commons/search/data/boreholeSearchData.js
=> Change qt-depth dropdown

CHANGELOG.md, src/client/src/pages/settings/admin/adminSettings.js, src/client/src/pages/settings/admin/workgroupRoleSettings.js, src/client/src/pages/settings/settingCmp.js
=> Admin ticks

CHANGELOG.md, src/client/src/commons/form/workflow/commentArea.js, src/client/src/commons/form/workflow/commentComponent.js, src/client/src/commons/form/workflow/workflowForm.js
=> Comment box layout

CHANGELOG.md, src/client/src/pages/settings/dataLoader.js
=> Load boreholes independently of borehole table

src/api/BdmsContextExtensions.cs
=> Use correct schema in bogus data

CHANGELOG.md, src/client/cypress/e2e/filter.cy.js, src/client/src/commons/search/editor/searchEditorComponent.js
https://github.com/geoadmin/suite-bdms/issues/231
=> Display filter by map in Editor if Large Map appearance

src/client/src/commons/map/mapComponent.js
#175 
Keine Release notes, da es eine Verbesserung eines noch nicht releasten neuen Features ist.
=> Improve clustering

src/client/src/commons/map/pointComponent.js
Resolves #177 
Keine Release notes, da es eine Verbesserung eines unreleaseden bugfix ist.
=> Reset point when unlocking without apply

src/client/src/commons/map/mapComponent.js
=> Adapt zoom when clicking on point

CHANGELOG.md, src/api-legacy/v1/action.py, src/api-legacy/v1/borehole/editinglist.py, src/client/cypress/e2e/filter.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/search/components/listFilter.js, src/client/src/commons/search/data/registrationSearchData.js, src/client/src/commons/search/editor/searchEditorComponent.js, src/client/src/commons/search/editor/searchEditorState.js, src/client/src/pages/settings/data/registrationEditorData.js, src/client/src/pages/settings/editorSettings.js
Resolves https://github.com/geoadmin/suite-bdms/issues/97
=> New filter registration

CHANGELOG.md, src/client/cypress/e2e/editor/coordinates.cy.js, src/client/cypress/e2e/srsFilter.cy.js, src/client/package-lock.json, src/client/package.json, src/client/src/commons/detail/detailsComponent.js, src/client/src/commons/detail/meta/metaComponent.js, src/client/src/commons/form/borehole/segments/coordinatesSegment.js, src/client/src/commons/table/boreholeEditorTable.js
=> Thousand seperators

CHANGELOG.md, src/client/src/commons/map/mapComponent.js
=> Fix execution of undefined prop functions.

CHANGELOG.md, src/api-legacy/v1/workflow/patch.py, src/api/BdmsContextExtensions.cs, src/api/Migrations/20230104130249_RemoveMentionsFromWorkflow.Designer.cs, src/api/Migrations/20230104130249_RemoveMentionsFromWorkflow.cs, src/api/Models/Workflow.cs, src/client/package-lock.json, src/client/package.json, src/client/src/api-lib/reducers/index.js, src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js, src/client/src/commons/form/borehole/segments/boreholeGeneralSegment.js, src/client/src/commons/form/borehole/segments/cantonMunicipalitySegment.js, src/client/src/commons/form/borehole/segments/coordinatesSegment.js, src/client/src/commons/form/borehole/segments/locationSegment.js, src/client/src/commons/form/borehole/segments/nameSegment.js, src/client/src/commons/form/borehole/segments/restrictionSegment.js, src/client/src/commons/form/workflow/commentComponent.js, src/client/src/commons/form/workflow/defaultStyle.js
=> Remove mentions functionality

src/client/src/commons/form/borehole/segments/locationSegment.js, src/client/src/commons/map/pointComponent.js
=> Fix map behaviour if page is left during editing

src/api-legacy/v1/workflow/list.py
=> Remove mentions from  list.py

CHANGELOG.md, src/client/src/commons/detail/meta/metaComponent.js, src/client/src/commons/detail/stratigrafy/profile/view/profileViewComponent.js, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js, src/client/src/commons/form/borehole/segments/boreholeGeneralSegment.js, src/client/src/commons/form/borehole/segments/coordinatesSegment.js, src/client/src/commons/form/formUtils.js, src/client/src/commons/form/profile/components/profileAttributes/components/profileAttributeList/profileAttributeList.js, src/client/src/commons/form/profile/components/profileInstrument/components/instrument/Instrument.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.js, src/client/src/stratigraphy/stratigraphy.js
=> Numeric number format

src/client/src/commons/detail/detailsComponent.js, src/client/src/commons/menu/editor/menuEditorSearch.js, src/client/src/commons/menu/explorer/menuExplorer.js, src/client/src/commons/table/boreholeTable.js
=> Add missing thousand separators

src/api/Migrations/20230110161542_AddOriginalLithologyField.cs
https://github.com/geoadmin/suite-bdms/issues/248
=> Correctly concatenate strings in SQL script

src/client/cypress/e2e/viewer/displayLayer.cy.js, src/client/package-lock.json, src/client/package.json
=> Bump cypress from 10.11.0 to 12.4.0

src/client/src/api/fetchApiV2.js, src/client/src/pages/settings/editor/codeListSettings.js
Habe beim prototypen der stratigraphy festgestellt, dass noch nicht alle Aufrufe der neuen Api richtig aufgeräumt sind
=> Refactor codelist settings

src/client/src/api/fetchApiV2.js, src/client/src/commons/detail/stratigrafy/profile/profileContainer.js, src/client/src/commons/detail/stratigrafy/profile/view/profileViewComponent.js
Refactoring das aus dem prototypen mit der Viewer Komponente der Stratigraphy stammt.
=> Refactor profile view

src/api/Controllers/UserController.cs, src/client/cypress/e2e/testHelpers.js, src/client/cypress/support/e2e.js
Try to make the test runs idempotent by resetting the user settings before each e2e test-
=> Stabilize cypress tests

src/client/src/commons/form/workflow/workflowForm.js
=> Improve null handling

CHANGELOG.md, src/client/src/commons/map/mapComponent.js
Reuse already created styles instead of creating always new ones.
Relates to #239
=> Improve style handling in map component

CHANGELOG.md, src/api-legacy/v1/borehole/geojson.py, src/client/src/commons/map/mapComponent.js, src/client/src/commons/map/pointComponent.js
Verringert die übertragene Datenmenge um ca. 40%.
Relates to #239
=> Remove unnecessary values from borehole GeoJSON

CHANGELOG.md, src/client/src/commons/detail/stratigrafy/profile/view/profileViewComponent.js
=> Streamline readonly display of empty properties

CHANGELOG.md, src/client/src/commons/map/pointComponent.js
=> Disable point editing if borehole is not locked

CHANGELOG.md, src/client/cypress/e2e/filter.cy.js, src/client/src/commons/search/searchComponent.js, src/client/src/commons/search/searchState.js
Resolves https://github.com/geoadmin/suite-bdms/issues/187
=> Add workgroup filter in viewer

CHANGELOG.md, src/api-legacy/v1/borehole/stratigraphy/clone.py
=> Copy m:n layer values when cloning a stratigraphy

CHANGELOG.md, src/api/Migrations/20230203051645_DropObsoleteGeodinFilesTable.Designer.cs, src/api/Migrations/20230203051645_DropObsoleteGeodinFilesTable.cs, src/api/Migrations/BdmsContextModelSnapshot.cs
=> Drop obsolete geodin_files table

src/api/Migrations/20230203101538_MakeLayerStratigraphyFKRequired.Designer.cs, src/api/Migrations/20230203101538_MakeLayerStratigraphyFKRequired.cs, src/api/Migrations/BdmsContextModelSnapshot.cs, src/api/Models/FaciesDescription.cs, src/api/Models/ILayerDescription.cs, src/api/Models/Layer.cs, src/api/Models/LithologicalDescription.cs, tests/LayerControllerTest.cs
Related to https://github.com/geoadmin/suite-bdms/issues/303
LithologicalDescription und FaciesDescription werden beim Löschen einer Bohrung mit Cascade Delete ebenfalls entfernt.
=> Make Stratigraphy Foreign Key in ILayerDescription required

.gitignore, .vscode/launch.json, .vscode/tasks.json, README.md
Funktioniert in den Dev-Containern und lokal.
=> Configure React debugger for VSCode

.gitattributes
in order to be able to parse CHANGELOG file correctly.
=> Configure Git to use LF line endings

CHANGELOG.md, src/api/Controllers/CantonController.cs, src/api/Controllers/FaciesDescriptionController.cs, src/api/Controllers/LayerController.cs, src/api/Controllers/LithologicalDescriptionController.cs, src/api/Controllers/LocationController.cs, src/client/src/commons/form/cantons/dropdown/cantonDropdown.js
=> Add missing API endpoint access scopes

CHANGELOG.md, src/client/src/App.js, src/client/src/api-lib/actions/index.js, src/client/src/commons/alert/alertBanner.js, src/client/src/commons/alert/alertContext.js, src/client/src/commons/feedback/feedbackComponent.js, src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/form/borehole/segments/indentifierSegment.js, src/client/src/commons/form/profile/components/profileAttributes/profileAttributes.js, src/client/src/commons/form/profile/components/profileInfo/profileInfo.js, src/client/src/commons/form/profile/components/profileInstrument/components/instrument/Instrument.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersError/profileLayersError.js, src/client/src/commons/form/workflow/workflowForm.js, src/client/src/commons/menu/editor/menuEditorSearch.js, src/client/src/commons/table/boreholeEditorTable.js, src/client/src/pages/settings/admin/adminSettings.js, src/client/src/pages/settings/components/editorSettingList/mapSettings.js, src/client/src/pages/settings/databaseSettings.js, src/client/src/pages/settings/editor/identifierSettings.js, src/client/src/pages/settings/explorerSettings.js, src/client/src/pages/settings/loginScreen.js
Replaces all generic alerts in react components
=> Replace alerts

BDMS.sln, CHANGELOG.md, src/api/BdmsContextExtensions.cs, src/api/Controllers/BoreholeController.cs, tests/BoreholeControllerTest.cs
Simplify test cleanup code along the way.
Fixes #331
=> Copy LayerCodelist when copying boreholes

src/api/Controllers/CodeListController.cs
=> Allow loading codelist data as viewer

CHANGELOG.md, src/api/Controllers/BoreholeController.cs
=> Allow copying a borehole as non-admin user

src/client/src/commons/form/profile/components/profileLayers/profileLayers.js, src/client/src/commons/form/profile/profile.js
=> Display lithological-description-only-in-stratigraphy

src/client/src/App.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/actionButtons.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionDeleteDialog.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionDisplay.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionInput.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionLayers.js
=> Insert top gap

CHANGELOG.md, src/client/cypress/e2e/editor/boreholeEditorTable.cy.js, src/client/src/commons/map/mapComponent.js, src/client/src/commons/table/boreholeEditorTable.js, src/client/src/pages/editor/editorComponent.js, src/client/src/pages/home/homeComponent.js
=> Improve navigation state handling

CHANGELOG.md, src/api/Controllers/BdmsControllerBase.cs, src/api/Controllers/CodeListController.cs, src/api/Controllers/FaciesDescriptionController.cs, src/api/Controllers/LayerController.cs, src/api/Controllers/LithologicalDescriptionController.cs
=> Fix editor update permissions

CHANGELOG.md, src/api/Controllers/BdmsControllerBase.cs, src/api/Controllers/FaciesDescriptionController.cs, src/api/Controllers/LayerController.cs, src/api/Controllers/LithologicalDescriptionController.cs
=> Fix editor delete permissions

CHANGELOG.md, src/client/cypress/e2e/app.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/src/App.js, src/client/src/commons/menu/menuComponent.js, src/client/src/commons/menu/settings/menuSettings.js, src/client/src/pages/settings/settingCmp.js
=> Navigate to correct mode when leaving settings

src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
Fixes unexpected display of zeros
=> Fix length check

src/client/cypress/e2e/editor/lithologicalDescription.cy.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/actionButtons.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionLayers.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.js, src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
=> Start edit on click

src/api/Controllers/BdmsControllerBase.cs, src/api/Controllers/FaciesDescriptionController.cs, src/api/Controllers/LayerController.cs, src/api/Controllers/LithologicalDescriptionController.cs
=> Add missing create permissions

src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/actionButtons.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionInput.js, src/client/src/commons/form/profile/components/profileLayers/components/lithologicalDescriptionLayers/lithologicalDescriptionLayers.js
=> Fix description not saved

CHANGELOG.md, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/pages/settings/editor/identifierSettings.js
=> Fix and update Identifier translation

CHANGELOG.md, src/api-legacy/v1/borehole/codelist/handler.py
=> Remove temporary workaround causing an error

src/client/src/pages/settings/editor/identifierSettings.js
=> Use correct translation key

src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
=> Fix datepicker-position and add spinner

CHANGELOG.md, src/client/src/api-lib/actions/index.js, src/client/src/pages/home/homeComponent.js
=> Fix profile download

CHANGELOG.md, src/client/src/api/fetchApiV2.js, src/client/src/commons/form/profile/components/profileHeader/profileHeader.js, src/client/src/commons/form/profile/components/profileInstrument/profileInstrument.js, src/client/src/commons/form/profile/profile.js, src/client/src/pages/settings/admin/adminSettings.js
=> Display Loader icon when fetching data from API v2

src/api-legacy/v1/borehole/export/profile/bdms_pdf.py
Changelog ist bereits nachgeführt.
Resolves #380
=> Fix PDF export

src/client/src/api-lib/actions/borehole.js, src/client/src/commons/table/tableComponent.js
Changelog ist bereits nachgeführt.
Resolves #188
=> Improve navigation experience with active map filter

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/actionButtons.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionDeleteDialog.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionInput.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionLayers.js
=> Prevent zero width layer

CHANGELOG.md, src/client/src/commons/form/profile/components/profileInstrument/api/index.js, src/client/src/commons/form/profile/hooks/useCasingList.js
Quick fix as too many (redundant) API calls are made in this component.
Resolves #426
=> Use react-query for fetching instruments

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/actionButtons.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionDeleteDialog.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionDisplay.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionLayers.js
=> Fix error when deleting two lithologies

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/profileLayersValidation.js
=> Scroll to new lithology layers

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersError/errorTypes/index.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersError/profileLayersError.js
Wie in der Wochensitzung angesprochen.
=> Remove set manually option

CHANGELOG.md, src/client/src/api/fetchApiV2.js, src/client/src/commons/form/profile/components/profileAttributes/profileAttributes.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/profileLayersValidation.js, src/client/src/commons/form/profile/components/profileLayers/profileLayers.js, src/client/src/commons/form/profile/profile.js
=> Display lithology props in layer overview

CHANGELOG.md, src/client/src/commons/form/borehole/segments/coordinatesSegment.js
=> Fix bug when pasting coordinates

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/profileLayersValidation.js, src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
=> Adapt delete options

src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionDisplay.js, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionLayers.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersError/profileLayersError.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersError/styles.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/profileLayersValidation.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/styles.js, src/client/src/commons/form/profile/components/profileLayers/profileLayers.js
=> Fix bugs bulkshift

src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.js
=> Remove keine Angaben from lithology preview

CHANGELOG.md, src/client/cypress/e2e/editor/emptyMessages.cy.js, src/client/cypress/e2e/editor/layerform.cy.js, src/client/cypress/e2e/editor/lithologicalDescription.cy.js, src/client/cypress/e2e/viewer/displayLayer.cy.js, src/client/src/commons/menu/editor/menuEditorForm.js
Resolves https://github.com/geoadmin/suite-bdms/issues/486
=> Change stratigraphy menu

CHANGELOG.md, src/client/cypress/e2e/editor/chronostratigraphy.cy.js, src/client/src/commons/form/profile/components/profileLayers/components/chronoStratigraphyLayers/layerCard.js
Resolves https://github.com/geoadmin/suite-bdms/issues/485
=> Display chronostratigraphy color

CHANGELOG.md, src/client/cypress/e2e/editor/instrumentation.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/cypress/fixtures/viewerUser.json, src/client/src/commons/form/profile/components/profileInstrument/profileInstrument.js
=> Resolve error when selecting Instrumentation with no EDIT role and no stratigraphy defined for borehole.

src/client/src/commons/menu/editor/menuEditorSearch.js
=> Remove breaks from csv upload preview

CHANGELOG.md, src/client/cypress/e2e/editor/instrumentation.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/cypress/e2e/viewer/displayLayer.cy.js
Fixes #482 
Optimized Instumentation tests.
Optimized DisplayLayer test.
=> Fix flaky instrumentation test

CHANGELOG.md, src/client/src/commons/form/profile/components/profileInstrument/profileInstrument.js
=> Improve rendering of instrumentation

src/client/src/commons/menu/editor/menuEditorSearch.js
=> Remove whitespace from import header

CHANGELOG.md, src/client/cypress/e2e/filter.cy.js, src/client/src/commons/menu/settings/menuSettings.js
=> Add editor mode settings for all user rights

CHANGELOG.md, src/api-legacy/v1/borehole/geojson.py, src/client/src/pages/home/homeComponent.js
=> Fix cluster map

CHANGELOG.md, src/client/src/commons/table/boreholeTable.js, src/client/src/commons/table/tableComponent.js
=> Page reset in viewer

CHANGELOG.md, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/profileLayersValidation.js
=> Fix scroll lithology layers

CHANGELOG.md, src/client/cypress/e2e/editor/chronostratigraphy.cy.js, src/client/src/commons/form/profile/components/profileInfo/components/infoCheckBox/infoCheckBox.js, src/client/src/commons/form/profile/components/profileInfo/profileInfo.js, src/client/src/commons/form/profile/profile.js
=> Remove clone and delete icons in chronostratigraphy header

CHANGELOG.md, src/client/src/commons/menu/editor/menuEditorSearch.js
=> Make csv import validation error modal content scrollable

docker-compose.yml, src/client/Dockerfile
=> Correctly build and deploy online help

src/client/Dockerfile
=> Copy help after building the app

CHANGELOG.md, src/api/Controllers/UploadController.cs, tests/UploadControllerTest.cs
=> Replace csv import validation messages

src/client/Dockerfile
=> Fix help path in docker file

src/client/cypress/e2e/editor/attachments.cy.js, src/client/cypress/e2e/testHelpers.js
=> Extend cypress test for file upload

src/client/Dockerfile
=> Copy online help before running npm build

src/api/BoreholeFileUploadService.cs, src/api/Controllers/BoreholeFileController.cs, tests/BoreholeFileControllerTest.cs, tests/BoreholeFileUploadServiceTest.cs, tests/UploadControllerTest.cs
=> Add additional info to borehole file

src/api/BdmsContextExtensions.cs, src/api/Controllers/StratigraphyController.cs, src/api/Controllers/WaterIngressController.cs, src/client/src/api/fetchApiV2.js, src/client/src/commons/form/borehole/hydrogeology/waterIngressDisplay.js, src/client/src/commons/form/borehole/hydrogeology/waterIngressInput.js, tests/StratigraphyControllerTest.cs
=> Link casing to wateringress input

src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/menu/editor/menuEditorForm.js
=> Fix wateringress translations

src/client/src/commons/form/borehole/hydrogeology/waterIngress.js, src/client/src/commons/form/borehole/hydrogeology/waterIngressInput.js
=> Fix datefield behaviour and margins

src/client/public/locale/de/common.json
=> Fix translation

src/client/src/commons/form/borehole/hydrogeology/waterIngress.js, src/client/src/commons/form/borehole/hydrogeology/waterIngressDisplay.js
=> Dont allow opening edit mask if other wateringress is edited

src/client/src/commons/form/borehole/hydrogeology/waterIngress.js, src/client/src/commons/form/borehole/hydrogeology/waterIngressDisplay.js
=> Behaviour wateringress on stop editing

src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/menu/editor/menuEditorForm.js
=> Fix wateringress translation

docker-compose.yml, src/api/BoreholeFileUploadService.cs, src/api/Controllers/BoreholeFileController.cs, src/api/Models/BoreholeFileUpdate.cs, src/api/Models/Hydrotest.cs, src/api/Models/HydrotestResult.cs, src/api/Program.cs, src/client/cypress/e2e/editor/attachments.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/src/api/fetchApiV2.js, src/client/src/commons/files/downloadlink.js, src/client/src/commons/files/table/editorBoreholeFilesTable.js, src/client/src/commons/files/table/filesTableComponent.js, tests/BoreholeControllerTest.cs, tests/BoreholeFileControllerTest.cs
=> Use .Net endpoints in legacy API

src/client/mkdocs.yml
Gemäss Input von @gysimichael in #558
=> Change site title of online help

CHANGELOG.md, src/api/Controllers/UploadController.cs, src/client/docs/import.md, tests/BDMS.Test.csproj, tests/BoreholeFileControllerTest.cs, tests/TestData/duplicateBoreholesInDbButDifferentWorkgroup.csv, tests/UploadControllerTest.cs
=> Duplicates per workgroup

src/client/src/commons/detail/meta/metaComponent.js
Resores original styling lost during refactor.
Fix for: https://github.com/geoadmin/suite-bdms/issues/497#issuecomment-1551286414
Resolves: #497
=> Fix flex direction of identifiers in viewer

CHANGELOG.md, src/api/Controllers/CodeListController.cs, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/api/fetchApiV2.js, src/client/src/commons/files/downloadlink.js, src/client/src/commons/files/table/filesTableComponent.js, src/client/src/commons/menu/editor/menuEditorSearch.js, tests/CodeListControllerTest.cs
=> Aktuelle Codelisten für Import dynamisch anbieten

src/client/src/commons/form/borehole/hydrogeology/parameterUnits.js
=> Define units in jsx

src/client/src/commons/form/borehole/hydrogeology/hydrotest.js
=> Fix sorting

src/client/src/commons/form/borehole/hydrogeology/fieldMeasurement.js, src/client/src/commons/form/borehole/hydrogeology/fieldMeasurementDisplay.js, src/client/src/commons/form/borehole/hydrogeology/fieldMeasurementInput.js, src/client/src/commons/form/borehole/hydrogeology/hydrotestResultTable.js, src/client/src/commons/form/borehole/hydrogeology/parameterUnits.js
=> Add unit adornement to fieldMeasurement value

src/client/src/commons/form/borehole/hydrogeology/parameterUnits.js
=> Remove dash from ph unit

src/api/HydroCodeLookup.cs
=> Allow adding hydrotest result when selecting testkind not specified

CHANGELOG.md, src/client/src/commons/form/borehole/hydrogeology/observationInput.js
=> Fix translation Ausbau fertiggestellt

src/client/src/commons/form/profile/data/fillingdata.js
=> Fix todepth labelk in filling

CHANGELOG.md, src/client/src/stratigraphy/stratigraphy.js
Resolves https://github.com/geoadmin/suite-bdms/issues/590
=> Fix lithology layer sorting in viewer

CHANGELOG.md, src/client/src/commons/menu/editor/menuEditorSearch.js
=> Workgroup scroll import

CHANGELOG.md, src/api/Controllers/BoreholeFileController.cs
=> Ensure borehole attachments can be managed by any user role

src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/menu/editor/menuEditorSearch.js
=> Import UI feedback

src/api/Controllers/BoreholeFileController.cs, src/api/Controllers/UploadController.cs, src/client/src/commons/files/table/editorBoreholeFilesTable.js, src/client/src/commons/menu/editor/menuEditorSearch.js, tests/UploadControllerTest.cs
=> Update max payload size for file upload

CHANGELOG.md, src/client/src/commons/form/borehole/hydrogeology/observationDisplay.js, src/client/src/commons/form/borehole/hydrogeology/observationInput.js
=> Add completion unknown to options in hydrogeology observations

CHANGELOG.md, src/api/Controllers/HydrotestController.cs, src/client/src/stratigraphy/stratigraphy.js
=> Allow creating hydrotest for normal user

src/client/cypress.config.js
=> Ensure interaction with element

src/client/package-lock.json, src/client/package.json, src/client/src/commons/detail/detailsComponent.js, src/client/src/commons/detail/stratigrafy/profile/view/profileViewComponent.js, src/client/src/commons/form/borehole/hydrogeology/observationDisplay.js, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.js, src/client/src/commons/form/borehole/segments/coordinatesSegment.js, src/client/src/commons/form/borehole/segments/restrictionSegment.js, src/client/src/commons/form/multiple/multipleForm.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/styles.js, src/client/src/commons/form/workflow/workflowForm.js, src/client/src/commons/menu/editor/menuEditorForm.js, src/client/src/commons/table/boreholeEditorTable.js, src/client/src/commons/table/tableComponent.js, src/client/src/pages/home/homeComponent.js, src/client/src/pages/settings/components/editorSettingList/editorSettingList.js, src/client/src/stratigraphy/stratigraphy.js
=> Update eslint prettier

src/client/src/api/fetchApiV2.js, src/client/src/commons/table/boreholeEditorTable.js
=> Use copyBorehole from fetchApiV2

CHANGELOG.md, docker-compose.yml, src/api-legacy/v1/basehandler.py, src/api-legacy/v1/borehole/ids.py, src/api/Authentication/LegacyApiAuthenticationMiddleware.cs, src/api/BDMS.csproj, src/api/Program.cs, src/api/appsettings.Development.json, src/api/appsettings.json, src/client/.env, src/client/src/setupProxy.js
=> Add yarp proxy

.github/workflows/ci.yml, README.md, docker-compose.yml, src/api/Program.cs
=> Await container startup before tests

CHANGELOG.md, src/client/src/commons/form/borehole/boreholeForm.js, src/client/src/commons/form/borehole/segments/cantonMunicipalitySegment.js, src/client/src/commons/form/borehole/segments/indentifierSegment.js, src/client/src/commons/form/borehole/segments/locationSegment.js, src/client/src/commons/form/borehole/segments/nameSegment.js, src/client/src/commons/form/borehole/segments/restrictionSegment.js, src/client/src/commons/form/dateField.js, src/client/src/commons/map/pointComponent.js
=> Disable inputs of the editor view's borehole location form

src/api/Controllers/InstrumentationController.cs, src/api/Models/Completion.cs, src/client/cypress/e2e/editor/instrumentation-v2.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/cypress/support/e2e.js, src/client/src/api/fetchApiV2.js, src/client/src/commons/form/borehole/completion/completion.js, src/client/src/commons/form/borehole/completion/completionContent.js, src/client/src/commons/form/borehole/completion/completionSchemaConstants.js, src/client/src/commons/form/borehole/completion/instrumentation.js, src/client/src/commons/form/borehole/completion/instrumentationDisplay.js, src/client/src/commons/form/borehole/completion/instrumentationInput.js, src/client/src/commons/form/borehole/completion/styledComponents.js
=> Instrumentation cards UI

CHANGELOG.md, src/api-legacy/v1/action.py, src/api/BoreholeLockService.cs, src/client/src/commons/menu/editor/menuEditorForm.js
=> Increase edit lock timeout to 60 minutes

CHANGELOG.md, src/api/BoreholeLockService.cs, tests/BoreholeLockServiceTest.cs
=> Admins can always edit boreholes

src/client/cypress/e2e/editor/backfill-v2.cy.js, src/client/cypress/e2e/editor/completion-v2.cy.js, src/client/cypress/e2e/editor/instrumentation-v2.cy.js, src/client/cypress/e2e/testHelpers.js, src/client/cypress/e2e/viewer/displayLayer.cy.js, src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/api/fetchApiV2.js, src/client/src/commons/form/borehole/completion/backfill.js, src/client/src/commons/form/borehole/completion/backfillDisplay.js, src/client/src/commons/form/borehole/completion/backfillInput.js, src/client/src/commons/form/borehole/completion/completionContent.js, src/client/src/commons/form/borehole/completion/completionSchemaConstants.js, src/client/src/commons/form/borehole/completion/instrumentation.js
=> Backfill cards

src/client/src/commons/menu/editor/menuEditorForm.js
=> Increase lock timeout

src/api/Authentication/DatabaseAuthenticationClaimsTransformation.cs
=> Fix race condition on user insert

src/client/public/locale/common.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/api-lib/reducers/index.js, src/client/src/pages/settings/dataLoader.js
Resolves: [#965](https://github.com/geoadmin/suite-bdms/issues/965)
=> Add feedback for disabled/unauthorized users

src/client/src/BdmsAuthProvider.js, src/client/src/pages/settings/dataLoader.js
=> Navigate route after login

src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
Resolves Code scanning alert [#12](https://github.com/geoadmin/suite-bdms/security/code-scanning/12)
=> Remove line breaks from user log input to prevent log forging

src/api-legacy/v1/action.py, src/api-legacy/v1/borehole/profile/layer/get.py, src/api-legacy/v1/borehole/stratigraphy/layer/get.py, src/api-legacy/v1/borehole/stratigraphy/layer/patch.py, src/client/cypress/e2e/filter.cy.js
=> Bugfix codelists

src/client/cypress/e2e/editor/layerform.cy.js, src/client/src/commons/form/domain/dropdown/domainDropdown.jsx, src/client/src/commons/form/profile/components/profileAttributes/components/profileAttributeList/profileAttributeList.jsx
Resolves [#256](https://github.com/geoadmin/suite-bdms/issues/256)
=> Bugfix layercodes

src/client/package.json, src/client/src/commons/auth/BdmsAuthProvider.jsx, src/client/src/index.jsx
Reintroduce changes lost during merge.
Remove obsolete configuration
Ref: [#866](https://github.com/geoadmin/suite-bdms/issues/866)
=> Fixup: Vite migration

CHANGELOG.md, src/client/src/commons/form/borehole/stratigraphy/layerCard.jsx, src/client/src/commons/form/borehole/stratigraphy/lithologyViewProfile.jsx
=> Remove square brackets from m MD

docker-compose.yml, src/client/Dockerfile
=> Fix client container port exposure with vite

CHANGELOG.md, src/client/src/commons/form/borehole/segments/coordinateSegmentInterfaces.ts, src/client/src/commons/form/borehole/segments/coordinatesSegment.tsx
=> Fix height reference system display

CHANGELOG.md, src/client/cypress/e2e/editor/hydrotest.cy.js, src/client/src/commons/form/borehole/hydrogeology/hydrotestDisplay.jsx
=> Bugfix hydrotest name

CHANGELOG.md, src/client/Dockerfile
=> Use non-root user to run the boreholes client web application

README.md
=> Add OIDC Documentation

src/client/cypress/e2e/editor/backfill.cy.js, src/client/cypress/e2e/editor/casing.cy.js, src/client/cypress/e2e/editor/fieldMeasurement.cy.js, src/client/cypress/e2e/editor/groundwaterLevelMeasurement.cy.js, src/client/cypress/e2e/editor/hydrotest.cy.js, src/client/cypress/e2e/editor/instrumentation.cy.js, src/client/cypress/e2e/editor/waterIngress.cy.js, src/client/cypress/e2e/helpers/testHelpers.js
Improve flaky tests by adding items via API, when the sorting of the items should be asserted.
=> Improve sorting tests

src/api/Controllers/BackfillController.cs, src/api/Controllers/InstrumentationController.cs, src/client/cypress/e2e/editor/backfill.cy.js, src/client/cypress/e2e/editor/instrumentation.cy.js, src/client/src/commons/form/borehole/completion/backfillDisplay.jsx, src/client/src/commons/form/borehole/completion/casingUtils.jsx, src/client/src/commons/form/borehole/completion/instrumentationDisplay.jsx
=> Fix casing completion select

.editorconfig
=> Define indent_size for jsx/ts/tsx to match prettier config

CHANGELOG.md, src/client/src/commons/form/borehole/completion/casingInput.jsx
=> Improve casing input mask

CHANGELOG.md, src/client/cypress/e2e/editor/lithologicalDescription.cy.js, src/client/src/AppTheme.js, src/client/src/commons/form/borehole/boreholeForm.jsx, src/client/src/commons/menu/editor/menuEditorForm.jsx, src/client/src/pages/settings/settingCmp.jsx
=> Fix routing and menu style

CHANGELOG.md, src/client/src/commons/form/domain/domainText.jsx, src/client/src/commons/form/domain/dropdown/domainDropdown.jsx, src/client/src/commons/form/domain/tree/domainTree.jsx, src/client/src/commons/form/translationText.jsx, src/client/src/commons/menu/menuComponent.jsx, src/client/src/commons/search/components/statusFilter.jsx, src/client/src/pages/settings/admin/adminSettings.jsx, src/client/src/reducers/index.js
Habs beim Estellen des Issues kurz analysiert und dann auch gleich umgesetzt.
Resolves #1195
=> Removed debug functionality

src/client/src/commons/form/borehole/boreholeForm.jsx, src/client/src/commons/search/editor/searchEditorComponent.jsx
... war noch etwas nicht gespeichert :(
=> Remove remaining developer state

src/client/src/commons/auth/BdmsAuthProvider.jsx
Ich würde das gern temporär auf main pushen, um zu testen, ob es einen Einfluss auf das Problem mit dem trailing slash im Issue #1187 hat. Es geht eben lokal aber auf dev etc. nicht.  Oder sollen wir lieber einen branch temporär auf dev deployen?
=> Try fix trailing slash urls

src/client/vite.config.js
=> Set absolute base url to support react routing

CHANGELOG.md, src/api/BdmsContextExtensions.cs, src/api/Migrations/20240411140757_RenameSpudDate.Designer.cs, src/api/Migrations/20240411140757_RenameSpudDate.cs, src/api/Models/SectionElement.cs, src/client/cypress/e2e/editor/sections.cy.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/form/borehole/borehole/sectionDisplay.jsx, src/client/src/commons/form/borehole/borehole/sectionInput.jsx, src/client/src/commons/form/multiple/multipleForm.jsx, tests/Controllers/SectionControllerTest.cs
see https://github.com/geoadmin/suite-bdms/issues/1102
=> Rename spud date

src/client/src/commons/auth/BdmsAuthProvider.jsx
=> Remove redirect uri normalization

CHANGELOG.md, src/client/src/AppTheme.js, src/client/src/commons/map/LayerSelectControl.jsx, src/client/src/commons/map/ZoomControls.jsx, src/client/src/commons/map/mapComponent.jsx
=> Change map icons

CHANGELOG.md, src/client/src/commons/menu/editor/menuEditorForm.jsx
=> Change menu order

src/client/cypress/e2e/editor/completion.cy.js, src/client/cypress/e2e/helpers/testHelpers.js
=> Add waits to test

CHANGELOG.md, src/client/cypress/e2e/editor/casing.cy.js, src/client/src/commons/form/borehole/completion/casingInput.jsx
=> From depth casing

CHANGELOG.md, src/api-legacy/v1/handlers/producer.py
=> Remove obsolete authorization check

CHANGELOG.md, src/client/src/commons/map/mapComponent.jsx, src/client/src/commons/map/pointComponent.jsx
=> Fix zoom level

.github/workflows/ci.yml
Remove obsolete branch-ignore setting
=> Remove obsolete branch-ignore setting

src/client/src/commons/map/mapComponent.jsx, src/client/src/commons/map/pointComponent.jsx, src/client/src/components/basemapSelector/basemapSelector.tsx, src/client/src/components/basemapSelector/basemaps.ts
Fix basemap selector appearance
Working on #1196
=> Fix map selection

src/client/src/commons/map/mapComponent.jsx
Working on #1196 
Fixed resolution change on basemap change and fixed hightlights
=> Fix basemap selection

src/client/src/commons/form/borehole/segments/userInterface.ts, src/client/src/commons/menu/editor/actions/actionsInterfaces.ts, src/client/src/commons/menu/editor/actions/actionsModal.tsx, src/client/src/commons/menu/editor/menuComponents/boreholeNumbersPreview.tsx, src/client/src/commons/menu/editor/menuComponents/importErrorModal.tsx, src/client/src/commons/menu/editor/menuComponents/menuComponentInterfaces.ts, src/client/src/commons/menu/editor/menuComponents/menuItems.tsx, src/client/src/commons/menu/editor/menuEditorSearch.jsx
=> UI sidebar refactoring

CHANGELOG.md, src/api/Controllers/UploadController.cs, tests/BDMS.Test.csproj, tests/Controllers/UploadControllerTest.cs, tests/TestData/precision_testdata.csv
=> Fix precision attribute

src/client/src/App.jsx, src/client/src/AppTheme.ts, src/client/src/commons/auth/SplashScreen.tsx, src/client/src/commons/files/fileDropzone.jsx, src/client/src/commons/form/borehole/stratigraphy/layerGap.jsx, src/client/src/commons/form/borehole/stratigraphy/lithologyViewProfile.jsx, src/client/src/commons/form/borehole/stratigraphy/navigationLens.jsx, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/actionButtons.jsx, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionDeleteDialog.jsx, src/client/src/commons/form/profile/components/profileLayers/components/descriptionLayers/descriptionLayers.jsx, src/client/src/commons/form/workflow/defaultStyle.js, src/client/src/commons/form/workflow/workflowForm.jsx, src/client/src/commons/map/layerSelectControl.jsx, src/client/src/commons/map/mapComponent.jsx, src/client/src/commons/map/sidebar.jsx, src/client/src/commons/map/zoomControls.jsx, src/client/src/commons/table/boreholeEditorTable.jsx, src/client/src/components/basemapSelector/basemapSelector.tsx, src/client/src/components/form/form.js, src/client/src/components/prompt/prompt.jsx, src/client/src/components/styledTabComponents.jsx, src/client/src/mui.theme.d.ts, src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx, src/client/src/pages/settings/editor/codeListSettings.jsx, src/client/src/pages/settings/editor/identifierSettings.jsx, src/client/src/pages/settings/editorSettings.jsx, src/client/src/pages/settings/settingCmp.jsx, src/client/src/pages/term/accept.jsx
Use App theme for background color and boxshadow, preparation for #1257
=> Apply theme

src/client/src/commons/form/borehole/borehole/geometry.jsx, src/client/src/commons/form/borehole/borehole/geometryChartNE.jsx, src/client/src/commons/form/borehole/borehole/geometryChartZ.jsx, src/client/src/commons/form/borehole/borehole/geometryTable.jsx
see: https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1105
=> Geometry chart with data projected to variable plane

src/client/cypress/e2e/editor/hydrotest.cy.js, src/client/src/components/form/formMultiSelect.jsx
=> Fix hydrotest reset

src/client/src/commons/map/mapComponent.jsx, src/client/src/commons/map/pointComponent.jsx, src/client/src/components/basemapSelector/basemaps.ts
=> Reset all minResolutions to 0.1

src/client/package-lock.json, src/client/package.json, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersValidation/styles.js, src/client/src/commons/menu/editor/bottomBar.tsx, src/client/src/commons/menu/editor/mapView.jsx, src/client/src/commons/menu/editor/sideDrawer.tsx, src/client/src/components/basemapSelector/basemapSelector.tsx, src/client/src/pages/editor/editorComponent.jsx, src/client/src/pages/settings/editorSettings.jsx
=> Some improvements

src/client/src/components/basemapSelector/basemaps.ts
Use detailed grey map and avoid bad requests
=> Use detailed grey map

src/client/public/locale/de/common.json, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.jsx
=> Fixes in tvd

src/client/src/commons/form/borehole/completion/completionHeaderDisplay.jsx, src/client/src/commons/form/borehole/hydrogeology/hydrotestDisplay.jsx, src/client/src/commons/menu/detailView/detailHeader.tsx, src/client/src/components/dataCard/dataDisplayCard.jsx
=> Fix detail header

src/api/Migrations/20240521161817_RemoveObsoleteGeometryFields.cs
Measured Depth is sometimes null
=> Fix RemoveObsoleteGeometryFields migration

src/client/src/commons/menu/mainView/bottomDrawer.tsx
=> Set bottom drawer height to 50% for all screens

src/client/src/commons/form/workflow/workflowForm.jsx
Resolves https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1319
=> Add scrollbar to publication status tab

src/client/docs/import.md, src/client/src/commons/menu/mainView/actions/importer/importModalContent.tsx
=> Remove top_bedrock_tvd, qt_top_bedrock_tvd_id from import

src/client/src/commons/form/borehole/segments/boreholeDetailSegment.jsx
=> Round all TVD values in General

src/client/cypress/e2e/editor/completion.cy.js, src/client/src/commons/form/profile/components/profileLayers/components/profileLayersList/profileLayersList.jsx
Resolves https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1338
=> Add border in lithology

src/client/cypress/e2e/editor/completion.cy.js
See https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1350
=> Temporarily disable flaky test

src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/commons/menu/detailView/detailSideNav.jsx, src/client/src/commons/menu/mainView/menuComponents/boreholeNumbersPreview.tsx
Resolves #1345 
Resolves #1347
=> Remove word break and add whitespace

src/client/src/commons/menu/detailView/detailHeader.tsx
=> Always show edit button on status page

src/client/src/commons/menu/detailView/detailHeader.tsx
Except for the publication UI
Resolves #1356
=> Show edit button only in edit workflow

CHANGELOG.md, src/client/src/commons/form/borehole/segments/boreholeDetailSegment.jsx
=> Move groundwater radio buttons

CHANGELOG.md, src/client/src/commons/menu/mainView/mainSideNav.tsx
=> Fixed filter badge

CHANGELOG.md, src/api-legacy/v1/action.py, src/api-legacy/v1/borehole/editinglist.py, src/api-legacy/v1/setting/patch.py, src/api/BdmsContextExtensions.cs, src/client/cypress/e2e/editor/boreholeTable.cy.js, src/client/cypress/e2e/editor/bulkedit.cy.js, src/client/cypress/e2e/editor/location.cy.js, src/client/src/pages/detail/form/location/nameSegment.jsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx, src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx, src/client/src/pages/overview/layout/mapView.jsx
=> Alternate name

src/api/Migrations/BdmsContextModelSnapshot.cs
Sync ContextModelSnapshot after moving [User](https://github.com/swisstopo/swissgeol-boreholes-suite/pull/1427) and [Workgroup](https://github.com/swisstopo/swissgeol-boreholes-suite/pull/1434) Controllers to new API
=> Sync contextSnapshot

src/api-legacy/v1/action.py, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx
=> Add coordinate columns

src/client/src/App.tsx, src/client/src/AppTheme.ts
Fix global style font and focus attribute
=> Fix some style

src/client/cypress/e2e/editor/labeling.cy.js, src/client/cypress/e2e/helpers/testHelpers.js, src/client/src/pages/detail/detailPage.tsx
=> Mock fetch to run cypress test for labeling area

src/client/src/components/legacyComponents/multiple/multipleForm.jsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx
Working on #1348 Das reset der scroll position hat auf DEV noch nicht funktioniert. ¯\_(ツ)_/¯
=> Fix reset scroll position

CHANGELOG.md, src/client/src/pages/overview/sidePanelContent/filter/statusFilter.jsx
=> Fix filter status display

CHANGELOG.md, src/client/cypress/e2e/editor/map.cy.js, src/client/src/App.tsx, src/client/src/components/map/mapComponent.jsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx, src/client/src/pages/overview/boreholeTable/bottomBar.tsx, src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx, src/client/src/pages/overview/layout/mapView.tsx, src/client/src/pages/overview/overViewContext.tsx
=> Preserve zoom level

src/client/src/components/map/mapComponent.jsx
=> compare after sorting

CHANGELOG.md, src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurementDisplay.jsx
=> Fix order of groundwater level measurement attributes

.github/workflows/ci.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, CHANGELOG.md, src/view-sync/Dockerfile, src/view-sync/README.md, src/view-sync/db-init/00_create_extension.sql, src/view-sync/db-init/01_pg_pass.sh, src/view-sync/db-init/02_pg_dump.sh, src/view-sync/db-init/03_pg_restore.sh, src/view-sync/db-init/04_delete_from_borehole.sql, src/view-sync/db-init/05_pg_dump.sh, src/view-sync/db-init/06_pg_restore.sh, src/view-sync/docker-compose.services.yml, src/view-sync/docker-compose.yml
Syncs free/published boreholes from a source to a target database.
#1367
=> Add view-sync

CHANGELOG.md, src/client/src/pages/detail/form/location/nameSegment.tsx, src/client/src/pages/overview/layout/mainSideNav.tsx
=> Hide online help and original_name in read-only mode

CHANGELOG.md, src/client/cypress/e2e/editor/boreholeform.cy.js, src/client/src/components/form/formContainer.tsx, src/client/src/components/form/formCoordinate.tsx, src/client/src/components/form/formInput.tsx, src/client/src/components/form/formSelect.tsx, src/client/src/components/form/numericFormatWithThousandSeparator.tsx, src/client/src/components/map/pointComponent.jsx, src/client/src/pages/detail/form/location/coordinatesSegment.tsx, src/client/src/pages/detail/form/location/elevationSegment.tsx, src/client/src/pages/detail/form/location/locationSegment.tsx
[#1321](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1321)
=> Style elevation segment

src/client/cypress/e2e/editor/coordinates.cy.js, src/client/src/api-lib/ReduxStateInterfaces.ts, src/client/src/pages/detail/form/location/coordinatesSegment.tsx
=> Fix coordinate reset

CHANGELOG.md, src/client/src/components/basemapSelector/basemapSelector.tsx
=> Fix basemap selector style

src/client/cypress/e2e/detailPage/boreholeform.cy.js, src/client/cypress/e2e/detailPage/location.cy.js, src/client/src/pages/detail/detailPageContent.jsx, src/client/src/pages/detail/form/location/nameSegment.tsx
=> Name segment

src/client/cypress/e2e/mainPage/bulkedit.cy.js, src/client/src/components/form/formBooleanSelect.tsx, src/client/src/components/legacyComponents/bulkedit/bulkEditForm.tsx, src/client/src/pages/overview/boreholeTable/bottomBar.tsx, src/client/src/pages/overview/sidePanelContent/commons/workgroupSelect.tsx, src/client/src/pages/overview/sidePanelContent/newBoreholePanel.tsx
=> Fix bulkedit

CHANGELOG.md, docker-compose.yml, src/api/Dockerfile, src/api/appsettings.Development.json, src/api/appsettings.json, src/client/cypress/e2e/settings/mapSettings.cy.js, src/view-sync/docker-compose.services.yml
=> Add data extraction API 

.github/workflows/ci.yml, CHANGELOG.md, src/client/cypress/e2e/detailPage/labeling.cy.js, src/client/cypress/e2e/helpers/testHelpers.js, src/client/src/api/dataextraction.js, src/client/src/api/file/file.ts, src/client/src/pages/detail/detailPage.tsx, src/client/src/pages/detail/detailPageContent.jsx, src/client/src/pages/detail/form/location/coordinateSegmentInterfaces.ts, src/client/src/pages/detail/form/location/coordinatesSegment.tsx, src/client/src/pages/detail/form/location/locationSegment.tsx, src/client/vite.config.js
=> Extract coordinates from attachment

src/client/cypress/e2e/settings/mapSettings.cy.js, src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx
Fixes layer sorting and flaky test
=> Fix flaky map settings test

src/client/src/AppTheme.ts
=> Improve textfield labels according to design

src/client/src/components/styledComponents.ts
=> Fix main container

CHANGELOG.md, src/client/src/pages/overview/sidePanelContent/customLayers/customLayersComponent.jsx
=> Fix scrollbar

docker-compose.yml
to ensure the integrity of the application.
=> Pin dataextraction api to a specific version

src/api/BoreholeFileCloudService.cs
=> Fix permission denied while writing temporary file

src/client/src/pages/detail/form/location/identifierSegment.tsx
Identifier dropdown could not be reset
=> Fix reset option

src/client/src/pages/overview/sidePanelContent/commons/workgroupSelect.tsx
legacy IIFE  sometimes causes update delays
=> Refactor workgroupSelect

docker-compose.yml
=> Update dataextraction api to v1.0.5

src/client/cypress/e2e/detailPage/location.cy.js, src/client/src/pages/detail/detailPage.tsx, src/client/src/pages/detail/detailPageContent.tsx, src/client/src/pages/detail/form/location/coordinatesSegment.tsx, src/client/src/pages/detail/form/location/locationPanel.tsx
=> Save with shortcut

src/client/cypress/e2e/detailPage/coordinates.cy.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/components/form/formSelect.tsx, src/client/src/pages/detail/form/location/coordinatesSegment.tsx
=> Add prompt when coordinate system is changed

CHANGELOG.md, src/client/cypress/e2e/detailPage/labeling.cy.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/api/file/file.ts, src/client/src/pages/detail/labeling/labelingPanel.tsx
Resolves [#1611](https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1611)
#1546
=> Add not found error message to data extraction

src/client/src/components/prompt/prompt.tsx, src/client/src/pages/detail/form/location/coordinatesSegment.tsx
Display warning also when coordinates havent changed yet
=> Coordinate change warning

src/client/src/pages/detail/detailHeader.tsx
=> Show firstname and lastname as updated by value

src/api/BoreholeLockService.cs, src/api/Controllers/BoreholeFileController.cs, src/api/IBoreholeLockService.cs, tests/api/BoreholeLockServiceTest.cs, tests/api/Controllers/BoreholeFileControllerTest.cs
=> Add permissions check before retrieving borehole file info

src/client/cypress/e2e/detailPage/coordinates.cy.js, src/client/cypress/e2e/helpers/testHelpers.js, src/client/src/components/form/formInput.tsx, src/client/src/components/map/pointComponent.jsx, src/client/src/pages/detail/form/location/elevationSegment.tsx, src/client/src/pages/detail/form/location/locationSegment.tsx
=> Fix height input

CHANGELOG.md, src/api-legacy/v1/borehole/geojson.py, src/client/src/pages/detail/detailHeader.tsx
=> Display name

CHANGELOG.md, src/client/src/api/borehole.ts, src/client/src/pages/detail/form/location/nameSegment.tsx
=> Add workgroup display to location tab

src/api/Controllers/BoreholeController.cs, src/client/cypress/e2e/completion/completion.cy.js, src/client/src/pages/detail/form/workflow/workflowForm.jsx, tests/api/Controllers/BoreholeControllerTest.cs
=> Bug borehole display lost

src/client/src/pages/detail/form/location/nameSegment.tsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx
Resolves #1659 and Resolves #1624
=> Hide workgroup column and input in anonymous mode

CHANGELOG.md, src/client/cypress/e2e/mainPage/boreholeTable.cy.js, src/client/src/pages/detail/detailHeader.tsx
=> Fix internal error alert

.github/workflows/pre-release.yml
https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1474
=> Add path to the Dockerfile

.github/workflows/pre-release.yml
https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1474
=> Fix Docker build context

src/client/src/pages/detail/detailPageContent.tsx
=> Optimise panel space for small screens

CHANGELOG.md, src/client/cypress/e2e/hydrogeology/groundwaterLevelMeasurement.cy.js, src/client/src/pages/detail/detailPageContent.tsx, src/client/src/pages/detail/form/completion/casingUtils.jsx, src/client/src/pages/detail/form/hydrogeology/Observation.ts, src/client/src/pages/detail/form/hydrogeology/fieldMeasurement.jsx, src/client/src/pages/detail/form/hydrogeology/fieldMeasurementDisplay.jsx, src/client/src/pages/detail/form/hydrogeology/fieldMeasurementInput.jsx, src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurement.tsx, src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurementDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurementInput.tsx, src/client/src/pages/detail/form/hydrogeology/hydrotestDisplay.jsx, src/client/src/pages/detail/form/hydrogeology/hydrotestInput.jsx, src/client/src/pages/detail/form/hydrogeology/observationDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/observationInput.tsx, src/client/src/pages/detail/form/hydrogeology/waterIngressDisplay.jsx, src/client/src/pages/detail/form/hydrogeology/waterIngressInput.jsx
#1689  noch ohne Daten Löschen
=> Remove groundwater fields

src/client/cypress/e2e/filters/filter.cy.js, src/client/src/pages/overview/sidePanelContent/filter/FilterChips.tsx
=> Fix translation and add test

CHANGELOG.md, src/client/cypress/e2e/detailPage/sections.cy.js, src/client/src/components/dataCard/dataInputCard.jsx, src/client/src/pages/detail/detailPageContent.tsx, src/client/src/pages/detail/form/borehole/boreholeForm.tsx, src/client/src/pages/detail/form/borehole/boreholePanel.tsx, src/client/src/pages/detail/form/borehole/boreholePanelInterfaces.ts, src/client/src/pages/detail/form/borehole/sectionInput.jsx, src/client/src/pages/detail/form/useFormWithSaveBar.ts, src/client/src/pages/detail/useSaveOnCtrlS.ts
=> Use save on ctrl s hook

src/api/BoreholeFileCloudService.cs
Fixes https://github.com/swisstopo/swissgeol-boreholes-suite/security/code-scanning/27
=> Do not log user-controlled data

src/client/src/pages/overview/sidePanelContent/filter/statusFilter.jsx
=> Fix translation key

src/client/src/components/legacyComponents/domain/dropdown/domainDropdown.jsx
=> Fix domainDropdown

CHANGELOG.md, src/client/src/pages/detail/form/workflow/workflowForm.jsx
=> Fix status translations

src/client/src/pages/overview/sidePanelContent/importer/importModal.tsx
=> Ensure file type resets when import modal closes

CHANGELOG.md, src/client/src/components/form/formInput.tsx
=> Fix date inputs

CHANGELOG.md, src/client/src/pages/detail/detailHeader.tsx, src/client/src/pages/detail/form/workflow/workflowForm.jsx
=> Fix badge color

src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/components/boreholeImportDropzone.tsx, src/client/src/pages/overview/sidePanelContent/commons/workgroupSelect.tsx
=> Fix upload panel style

CHANGELOG.md, src/client/src/assets/icons/sidebarDown.svg, src/client/src/assets/icons/sidebarLeft.svg, src/client/src/assets/icons/sidebarRight.svg, src/client/src/assets/icons/sidebarUp.svg, src/client/src/components/buttons/labelingButton.tsx
=> Change labeling area icon

src/client/docs/import.md
#1710 
Add ZIP Import Section to help
=> Adapt help

CHANGELOG.md, src/client/cypress/e2e/viewer/viewer.cy.js, src/client/src/components/export/exportDialog.tsx, src/client/src/pages/detail/detailHeader.tsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx, src/client/src/pages/overview/boreholeTable/bottomBar.tsx
=> Export for anonymous mode

src/client/cypress/e2e/detailPage/attachments.cy.js, src/client/src/components/legacyComponents/formUtils.ts, src/client/src/pages/detail/form/borehole/boreholePanelInterfaces.ts, src/client/src/pages/detail/form/location/locationPanelInterfaces.tsx
Fixes bug introduced with #1710
=> Fix borehole update with files

CHANGELOG.md, src/client/cypress/e2e/detailPage/boreholeform.cy.js, src/client/cypress/e2e/helpers/buttonHelpers.js, src/client/src/components/form/formInput.tsx, src/client/src/pages/detail/form/borehole/boreholeForm.tsx, src/client/src/pages/detail/form/location/elevationSegment.tsx
=> Fix tvd reset

CHANGELOG.md, src/client/src/AppTheme.ts
Resolves #1395 
Remove asterisks
=> Remove asterisks from forms

CHANGELOG.md, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/pages/overview/sidePanelContent/importer/importPanel.tsx
In Absprache mit  @gysimichael
=> Include downloadlink

CHANGELOG.md, src/client/cypress/e2e/mainPage/bulkedit.cy.js, src/client/src/api-lib/ReduxStateInterfaces.ts, src/client/src/api/borehole.ts, src/client/src/components/bulkedit/bulkEditDialog.tsx, src/client/src/pages/overview/boreholeTable/bottomBar.tsx, src/client/src/pages/overview/boreholeTable/bottomBarContainer.tsx, src/client/src/pages/overview/layout/mainSideNav.tsx, src/client/src/pages/overview/overviewPage.tsx, src/client/src/pages/overview/sidePanelContent/commons/actionsInterfaces.ts, src/client/src/pages/overview/sidePanelContent/commons/workgroupSelect.tsx
=> Fix workgroup select

src/api/BoreholeFileCloudService.cs, src/api/Controllers/BoreholeFileController.cs, src/api/Controllers/ImportController.cs, tests/api/BoreholeFileCloudServiceTest.cs, tests/api/Controllers/BoreholeFileControllerTest.cs, tests/api/Controllers/ExportControllerTest.cs
Siehe Kommentar [hier](https://github.com/swisstopo/swissgeol-boreholes-suite/pull/1805#discussion_r1918582137)
Resolves #1819
=> Refactor BoreholeFileCloudService.cs

CHANGELOG.md, src/client/src/AppTheme.ts, src/client/src/components/styledTabComponents.tsx, src/client/src/mui.theme.d.ts, src/client/src/pages/detail/form/borehole/boreholeForm.tsx, src/client/src/pages/detail/form/borehole/boreholePanel.tsx, src/client/src/pages/detail/form/completion/completion.jsx, src/client/src/pages/detail/form/completion/completionContent.jsx, src/client/src/pages/overview/sidePanelContent/importer/boreholeImportDropzone.tsx, src/client/src/pages/overview/sidePanelContent/importer/importPanel.tsx
=> Fix tab style

CHANGELOG.md, src/api/BDMS.csproj, src/api/BoreholeExtensions.cs, src/api/BoreholeGeometryExtensions.cs, src/api/Controllers/ExportController.cs, src/client/src/api/borehole.ts, src/client/src/api/fetchApiV2.js, src/client/src/components/export/exportDialog.tsx, src/client/src/utils.ts, tests/api/Controllers/ExportControllerTest.cs
=> Geopackage export

CHANGELOG.md, src/client/cypress/e2e/detailPage/boreholeform.cy.js, src/client/src/AppTheme.ts, src/client/src/components/form/formCoordinate.tsx, src/client/src/components/form/formInput.tsx, src/client/src/components/form/formInputDisplayOnly.tsx, src/client/src/components/form/formSelect.tsx, src/client/src/components/header/headerComponent.tsx, src/client/src/components/legacyComponents/formUtils.ts, src/client/src/components/styledComponents.ts, src/client/src/components/styledTabComponents.tsx, src/client/src/mui.theme.d.ts, src/client/src/pages/detail/attachments/table/editorBoreholeFilesTable.tsx, src/client/src/pages/detail/detailSideNav.tsx, src/client/src/pages/detail/form/location/elevationSegment.tsx, src/client/src/pages/detail/form/location/nameSegment.tsx, src/client/src/pages/detail/form/stratigraphy/lithology/lithology.jsx, src/client/src/pages/detail/form/stratigraphy/stratigraphySelection.jsx, src/client/src/pages/detail/form/workflow/workflowForm.jsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx, src/client/src/pages/overview/boreholeTable/bottomBar.tsx, src/client/src/pages/overview/layout/sideDrawerHeader.tsx
=> Border color when editable

CHANGELOG.md, src/client/src/pages/detail/form/borehole/boreholeForm.tsx
=> Missing borehole general tab scrollbar

src/client/src/components/tabs/tabPanel.tsx, src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx
=> Fix tabs content overflow

src/client/cypress.config.js, src/client/cypress/e2e/admin/userAdministration.cy.js, src/client/cypress/e2e/completion/casing.cy.js, src/client/cypress/e2e/completion/completion.cy.js, src/client/cypress/e2e/detailPage/boreholeform.cy.js, src/client/cypress/e2e/detailPage/coordinates.cy.js, src/client/cypress/e2e/detailPage/sections.cy.js, src/client/cypress/e2e/helpers/buttonHelpers.js, src/client/cypress/e2e/helpers/dataGridHelpers.js, src/client/cypress/support/e2e.js
Improve cypress configuration and tests
=> Cypress config

src/client/server.cjs
=> Set security headers before serving static content

src/client/server.cjs
=> Allow connecting to AWS Cognito IdP

src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/pages/settings/admin/userDetail.tsx
Add missing column to workgroups table
=> Add missing column to user detail table

src/client/src/AppTheme.ts
=> Do not allow cards to shrink

CHANGELOG.md, src/api/BoreholeLockService.cs, src/api/Controllers/ExportController.cs, src/api/IBoreholeLockService.cs, tests/api/BoreholeLockServiceTest.cs, tests/api/Controllers/ExportControllerTest.cs
=> Export boreholes filter workgroup

src/client/server.cjs, src/client/vite.config.js
=> Update CSP header

src/client/src/api/fetchApiV2.js
=> Fix export for boreholes without name

src/client/src/pages/settings/admin/userDetail.tsx
=> Remove borehole count column

CHANGELOG.md, src/client/src/pages/detail/form/hydrogeology/parameterUnits.tsx
=> Change unit label from Pa to kPa

CHANGELOG.md, src/client/cypress/e2e/helpers/buttonHelpers.js, src/client/src/components/export/exportDialog.tsx
=> Add export spinner

src/api/Controllers/BoreholeGeometryController.cs, src/client/cypress/e2e/hydrogeology/waterIngress.cy.js, src/client/src/pages/detail/form/hydrogeology/observationInput.tsx, tests/api/Controllers/BoreholeGeometryControllerTest.cs
Resolves #1895 
Ist ein follow up PR daher kein Changelog-Eintrag.
Siehe Kommentar:
https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1895#issuecomment-2700019775
=> Change dropdown calculate depth masl

CHANGELOG.md, src/client/cypress/e2e/mainPage/boreholeTable.cy.js, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx
=> Fix purpose sorting

CHANGELOG.md, README.md, src/api/Controllers/SettingsController.cs, src/api/Models/Settings.cs, src/api/appsettings.json, src/client/cypress/e2e/app.cy.js, src/client/package-lock.json, src/client/package.json, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/server.cjs, src/client/src/api/SettingsProvider.tsx, src/client/src/api/useSettings.ts, src/client/src/auth/BdmsAuthProvider.jsx, src/client/src/components/form/formCheckbox.tsx, src/client/src/index.jsx, src/client/src/term/accept.tsx, src/client/src/term/disclaimerDialog.tsx, tests/api/Controllers/SettingsControllerTest.cs
https://github.com/swisstopo/swissgeol-assets-suite/issues/432
=> Add Google Analytics tracking

CHANGELOG.md, docker-compose.yml, src/client/cypress/e2e/detailPage/labeling.cy.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/AppTheme.ts, src/client/src/api/dataextraction.js, src/client/src/api/file/file.ts, src/client/src/components/alert/alertManager.tsx, src/client/src/mui.theme.d.ts, src/client/src/pages/detail/labeling/labelingDrawContainer.tsx, src/client/src/pages/detail/labeling/labelingInterfaces.tsx, src/client/src/pages/detail/labeling/labelingPanel.tsx
=> Labeling highlight words

src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/term/disclaimerFallback.js
https://github.com/swisstopo/swissgeol-assets-suite/issues/432
=> Add data collection information

CHANGELOG.md, src/client/cypress/e2e/hydrogeology/groundwaterLevelMeasurement.cy.js, src/client/cypress/e2e/hydrogeology/hydrotest.cy.js, src/client/src/components/form/formDisplay.tsx, src/client/src/components/form/formUtils.ts, src/client/src/pages/detail/form/completion/casingDisplay.jsx, src/client/src/pages/detail/form/hydrogeology/fieldMeasurement/fieldMeasurementDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/hydrotest/hydrotestDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/hydrotest/hydrotestInput.tsx, src/client/src/pages/detail/form/location/coordinatesSegment.tsx, src/client/src/pages/overview/boreholeTable/boreholeTable.tsx, src/client/src/utils.ts
=> Display small numbers in scientific notation

.github/workflows/ci.yml
Siehe Job Summary unter https://github.com/swisstopo/swissgeol-boreholes-suite/actions/runs/13974806100
=> Upload and show .NET API test results during CI

BDMS.sln, BDMS.slnLaunch, README.md
And include README in solution explorer.
=> Enable multi-project launch profile

CHANGELOG.md, src/client/src/term/disclaimerFallback.js
=> Update legal links in disclaimerFallback

CHANGELOG.md, src/client/src/pages/detail/form/borehole/geometryChartZ.jsx, src/client/src/pages/detail/form/borehole/geometryTable.jsx
=> Add 1000 separators to geometry

src/client/cypress/e2e/settings/mapSettings.cy.js, src/client/src/pages/settings/components/editorSettingList/mapSettings.jsx, src/client/src/pages/settings/generalSettings.tsx, src/client/src/pages/settings/termSettings.jsx
Remove semantic ui from settings
=> Remove semantic UI

src/client/src/pages/detail/form/stratigraphy/lithology/lithologyLayers/descriptionLayers/descriptionInput.jsx
=> Fix spaces around description input labels

CHANGELOG.md, src/client/cypress/e2e/mainPage/copyBorehole.cy.js, src/client/src/pages/overview/boreholeTable/bottomBar.tsx
=> Copy borehole to selected workgroup

CHANGELOG.md, src/client/src/App.tsx, src/client/src/pages/detail/detailPage.tsx, src/client/src/term/accept.tsx, src/client/src/term/analyticsContext.tsx, src/client/src/term/disclaimerDialog.tsx
=> Detailpage Google Analytics

src/client/cypress/e2e/detailPage/legacyWorkflow.cy.js, src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/src/pages/detail/detailPageContent.tsx, src/client/src/pages/detail/form/workflow/legacyWorkflowForm.jsx, src/client/src/pages/detail/form/workflow/workflowForm.tsx, src/client/src/pages/detail/form/workflow/workflowPanel.tsx
Add feature flag for workflow development
#2044
=> Workflow feature flag

CHANGELOG.md, src/view-sync/README.md, src/view-sync/config/pgadmin4-servers.json, src/view-sync/db-init/04_delete_from_borehole.sql, src/view-sync/docker-compose.services.yml
=> Fix view sync with existing default workgroup

src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurement/groundwaterLevelMeasurementDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/observationDisplay.tsx
See https://github.com/swisstopo/swissgeol-boreholes-suite/issues/1786
=> Reorder hydrogeology depth display fields

src/client/src/pages/detail/form/workflow/checkboxTable.tsx, src/client/src/pages/detail/form/workflow/workflowTabs.tsx, src/client/src/pages/detail/form/workflow/workflowView.tsx
=> Add readonly publish tab

src/api/BdmsContext.cs, src/api/BoreholePermissionService.cs, src/api/Controllers/WorkflowController.cs, src/api/IBoreholePermissionService.cs, src/api/Models/WorkflowChangeRequest.cs, src/client/src/pages/detail/form/workflow/workflow.ts, tests/api/BoreholePermissionServiceTest.cs, tests/api/Controllers/BackfillControllerTest.cs, tests/api/Controllers/BoreholeControllerTest.cs, tests/api/Controllers/BoreholeFileControllerTest.cs, tests/api/Controllers/BoreholeGeometryControllerTest.cs, tests/api/Controllers/CasingControllerTest.cs, tests/api/Controllers/ChronostratigraphyControllerTest.cs, tests/api/Controllers/CompletionControllerTest.cs, tests/api/Controllers/ExportControllerTest.cs, tests/api/Controllers/FaciesDescriptionControllerTest.cs, tests/api/Controllers/FieldMeasurementControllerTest.cs, tests/api/Controllers/GroundwaterLevelMeasurementControllerTest.cs, tests/api/Controllers/HydrotestControllerTest.cs, tests/api/Controllers/InstrumentationControllerTest.cs, tests/api/Controllers/LayerControllerTest.cs, tests/api/Controllers/LithologicalDescriptionControllerTest.cs, tests/api/Controllers/LithostratigraphyControllerTest.cs, tests/api/Controllers/PhotoControllerTest.cs, tests/api/Controllers/SectionControllerTest.cs, tests/api/Controllers/StratigraphyControllerTest.cs, tests/api/Controllers/WaterIngressControllerTest.cs, tests/api/Controllers/WorkflowControllerTest.cs
#2044 
Add workflow change request
=> Update workflow backend

CHANGELOG.md, src/client/cypress/e2e/stratigraphy/chronostratigraphy.cy.js, src/client/cypress/e2e/stratigraphy/lithostratigraphy.cy.js, src/client/src/pages/detail/form/stratigraphy/layerCard.jsx
=> Fix inputs for large numbers

CHANGELOG.md, src/client/cypress/e2e/admin/workgroupAdministration.cy.js, src/client/src/api/workgroup.ts, src/client/src/pages/settings/admin/workgroupDetail.tsx, src/client/src/pages/settings/settingsHeader.tsx
=> Workgroup name editable

CHANGELOG.md, src/api/Controllers/StratigraphyController.cs, tests/api/Controllers/StratigraphyControllerTest.cs
=> Copy lithostratigraphy when copying a stratigraphy

src/client/src/components/map/clickablePopup.tsx
=> Add hover effect on tooltip

CHANGELOG.md, src/api/Models/BoreholeFile.cs, src/api/Models/File.cs, src/api/Models/Photo.cs, src/api/Models/Workflow.cs, src/api/Models/WorkflowV2.cs, src/client/cypress/e2e/detailPage/labeling.cy.js
=> Fix save error

src/client/cypress/e2e/helpers/testHelpers.js
Noch aus dem letzten PR übriggeblieben
=> Remove empty line

src/api/Controllers/WorkflowController.cs, src/api/Models/WorkflowTabStatusChangeRequest.cs, src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/cypress/e2e/helpers/swissgeolCoreHelpers.ts, src/client/cypress/e2e/helpers/testHelpers.js, src/client/src/pages/detail/form/workflow/workflow.ts, src/client/src/pages/detail/form/workflow/workflowView.tsx, tests/api/Controllers/WorkflowControllerTest.cs
#2045 
#2046 
Implement tab status UI
=> Update tab status UI

src/api/BdmsContext.cs, src/api/Controllers/WorkflowController.cs, src/api/Migrations/BdmsContextModelSnapshot.cs, src/api/Models/WorkflowChangeRequest.cs, src/client/cypress/e2e/detailPage/legacyWorkflow.cy.js, src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/public/locale/de/common.json, src/client/public/locale/en/common.json, src/client/public/locale/fr/common.json, src/client/public/locale/it/common.json, src/client/src/AppTheme.ts, src/client/src/components/buttons/buttons.tsx, src/client/src/mui.theme.d.ts, src/client/src/pages/detail/detailHeader.tsx, src/client/src/pages/detail/form/workflow/statusColorMap.ts, src/client/src/pages/detail/form/workflow/workflow.ts, src/client/src/pages/detail/form/workflow/workflowView.tsx, src/client/src/pages/detail/statusBadges.tsx, tests/extern-sync/TestSyncContextExtensions.cs
#2045 
Badges werden im Detailheader angezeigt, wenn ?dev=true in der URL vorhanden ist
=> Fix badges

src/api/BdmsContext.cs, src/api/Migrations/20250710115322_AddPropertyToTabStatus.Designer.cs, src/api/Migrations/20250710115322_AddPropertyToTabStatus.cs, src/api/Models/TabStatus.cs, src/api/Models/WorkFlowStatusField.cs, src/client/src/pages/detail/form/workflow/workflowView.tsx
=> Fix review tab labels

.github/workflows/ci.yml, CHANGELOG.md, README.md, src/client/Dockerfile
=> Upgrade to Node 22 LTS

src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/cypress/e2e/helpers/swissgeolCoreHelpers.ts, src/client/src/hooks/useUserRoleForBorehole.ts, src/client/src/pages/detail/form/workflow/workflowView.tsx
=> Fix editor privileges

src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/src/pages/detail/detailSideNav.tsx, src/client/src/pages/detail/form/workflow/workflow.ts
=> Display checkmarks on sidemenu

CHANGELOG.md, src/client/src/components/dataCard/dataCards.tsx, src/client/src/components/styledTabComponents.tsx
=> Layout issue

src/client/src/pages/overview/sidePanelContent/filter/listFilter.tsx, src/client/src/pages/settings/admin/workgroupDetail.tsx
=> Increase debounce value

src/client/cypress/e2e/admin/userAdministration.cy.js, src/client/cypress/e2e/detailPage/workflow.cy.js, src/client/src/pages/detail/form/workflow/workflowView.tsx
=> Fix publish button disable

CHANGELOG.md, docker-compose.yml
=> Upgrade swissgeol OCR service to version 1.1.0

src/client/cypress/e2e/completion/completion.cy.js, src/client/cypress/e2e/viewer/viewer.cy.js, src/client/src/hooks/useBlockNavigation.tsx
Disable some cypress test and potentially fix flakyness issue
Working on #2260
=> Disable some tests

src/client/src/components/dataCard/dataDisplayCard.tsx, src/client/src/pages/detail/form/borehole/sectionDisplay.jsx, src/client/src/pages/detail/form/completion/backfillDisplay.jsx, src/client/src/pages/detail/form/completion/casingDisplay.jsx, src/client/src/pages/detail/form/completion/instrumentationDisplay.jsx, src/client/src/pages/detail/form/hydrogeology/fieldMeasurement/fieldMeasurementDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/groundwaterLevelMeasurement/groundwaterLevelMeasurementDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/hydrotest/hydrotestDisplay.tsx, src/client/src/pages/detail/form/hydrogeology/waterIngress/waterIngressDisplay.tsx
=> Fix reset tab status on card delete

src/client/src/pages/detail/form/workflow/workflowView.tsx
=> Fix disabled prop

CHANGELOG.md, src/client/src/pages/overview/sidePanelContent/filter/filterComponent.tsx, src/client/src/pages/overview/sidePanelContent/filter/listFilter.tsx
=> Remove filter in view

src/api/Controllers/LithologicalDescriptionController.cs, src/api/Controllers/LithologyController.cs, tests/api/Controllers/LithologicalDescriptionControllerTest.cs, tests/api/Controllers/LithologyControllerTest.cs
Voraussetzung um extrahierte Stratigraphien speichern zu können.
! Achtung Lithological Description ist noch mit StratigraphyV1 verbunden. Muss nach der Datenmigration angepasst werden.
#1963
=> Bulk add lithology

src/client/src/api/file/file.ts
=> Fix layer cleanup

src/client/src/components/codelist.ts, src/client/src/pages/detail/form/stratigraphy/stratigraphyV2/lithologyV2/lithologyContentEdit.tsx, src/client/src/pages/detail/form/stratigraphy/stratigraphyV2/lithologyV2/lithologyLabels.tsx
=> Update labels on tmp change

src/api/Controllers/LithologicalDescriptionController.cs, src/client/src/api/stratigraphy.ts, src/client/src/pages/detail/form/stratigraphy/extraction/stratigraphyExtractionDialog.tsx, src/client/src/pages/detail/form/stratigraphy/extraction/stratigraphyExtractionView.tsx, src/client/src/pages/detail/form/stratigraphy/extraction/useBulkAddMutations.ts
=> Add bulk save for extracted descriptions
